version: '3.9'

services:
  db:
    image: postgres:15
    container_name: cryptotrack_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cryptotrack
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    container_name: cryptotrack_app
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    # volumes:        # ← убрано, чтобы не затирать бинарник
    command: ["./bin/cryptotrack"]   # путь совпадает с Dockerfile

volumes:
  db_data:
